{{- range .Values.students }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook
  namespace: student-{{ .id }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      serviceAccountName: student-sa
      containers:
      - name: jupyter
        image: jupyter/base-notebook:latest
        ports:
        - containerPort: 8888
        resources:
          requests:
            memory: {{ $.Values.quota.memoryRequest }}
            cpu: {{ $.Values.quota.cpuRequest }}
          limits:
            memory: {{ $.Values.quota.memoryLimit }}
            cpu: {{ $.Values.quota.cpuLimit }}
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
  namespace: student-{{ .id }}
spec:
  selector:
    app: jupyter
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888
  type: ClusterIP
---
{{- end }}