students:
  - id: "01"
  - id: "02"

namespace:
  expiresAt: "2026-06-01"
  createdBy: "admin"

quota:
  cpuRequest: "0.5"
  cpuLimit: "1"
  memoryRequest: "512Mi"
  memoryLimit: "1Gi"
  maxPods: "3"                 # Jupyter + PostgreSQL + Web
  maxDeployments: "2"
  maxServices: "1"
  storageRequest: "3Gi"
  maxPVCs: "1"

networkPolicy:
  enabled: true               # set false if CNI doesn't support it (Docker Desktop kindnet)
  allowDnsEgress: true

rbac:
  enabled: true

prometheus:
  enabled: true

storage:
  size: "3Gi"
  className: "standard"   # Minikube default storage class

workload:
  enabled: true
  jupyter:
    image: "quay.io/jupyter/base-notebook:2025-01-20"
    port: 8888
  postgres:
    image: "postgres:15-alpine"
    port: 5432
    password: "student123"
